// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using сoursework.Data.Models;

namespace сoursework.Migrations
{
    [DbContext(typeof(BookStoreDBContext))]
    [Migration("20211014130520_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("сoursework.Data.Models.Book", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("cost")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgAlterText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisherСode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("topicid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("year")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("topicid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("сoursework.Data.Models.Topic", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("сoursework.Data.Models.Book", b =>
                {
                    b.HasOne("сoursework.Data.Models.Topic", "topic")
                        .WithMany("books")
                        .HasForeignKey("topicid");

                    b.Navigation("topic");
                });

            modelBuilder.Entity("сoursework.Data.Models.Topic", b =>
                {
                    b.Navigation("books");
                });
#pragma warning restore 612, 618
        }
    }
}
